-- | This module should be imported in place of the @GT.Prelude@ module.
-- Generally speaking, whenever there exists an @.Prelude@ module in the
-- codebase, prefer to import that instead of the Prelude.
module GT.DB.Prelude
    ( mkModel
    , loadModel
    -- * Reexports
    , module GT.Prelude
    , SqlPersistT
    , Entity(..)
    , OnlyOneUniqueKey(..)
    , AtLeastOneUniqueKey(..)
    ) where

import GT.Prelude

import Database.Persist.Quasi
import Database.Persist.Sql
import Database.Persist.TH
import Language.Haskell.TH

mkModel :: [EntityDef] -> DecsQ
mkModel = mkPersist sqlSettings

-- | We use 'loadModel' because we need to care about the migrations for
-- right now. At some point in the future, we'll move away from
-- @persistent@ autogenerated migrations and instead we'll use explicit SQL
-- migrations. At that point, we can move to the QuasiQuoter approach,
-- which will reduce file boilerplate and indirection.
loadModel :: String -> Q Exp
loadModel fileName =
    persistFileWith
        lowerCaseSettings ("schema/" <> fileName <> ".persistentmodels")
